spring.application.name=troubleshooter

spring.datasource.url=jdbc:mysql://securebigserver.synology.me:3306/troubleshooter?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=root
spring.datasource.password=prkty
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========= JPA ?? =========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========= ??? ?? (??) =========
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# GitHub Personal Access Token
github.token=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